[package]
name = "mwse_docs_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
env_logger = "0.11.6"
log = "0.4.26"
tokio = { version = "1.43.0", features = ["full"] }
